### ISSUE TITLE
Typographical Errors

### ISSUE THREAD

**Issue by evandrix** [myrtus0x0/SMAT#1]
[https://github.com/myrtus0x0/SMAT/blob/main/README.md](https://github.com/myrtus0x0/SMAT/blob/main/README.md)
1. ... environment ~~varialbes~~ variables...
2. ...SMAT allows for ~~anaylysts~~ analysts to quickly...

**Comment by wikijm** [comment]
Hi @evandrix 

I've made the pull request https://github.com/myrtus0x0/SMAT/pull/2 to handle the typo you reported 😉 

Regards,
WikiJM

**Comment by myrtus0x0** [comment]
Resolved via https://github.com/myrtus0x0/SMAT/pull/2
